[tool.poetry]
name = "server"
version = "0.1.0"
description = ""
authors = ["Mir Sahib"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.115.8"
uvicorn = "^0.33.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


